remote_theme: pmarsceill/just-the-docs@v0.3.3
title: Treefrog Handbook
lang: en-CA

exclude: ["Blank.md", "BestPractices", "DroppedChanges", "Goals"]

readme_index:
  remove_originals: true
  with_frontmatter: true

optional_front_matter:
  remove_originals: true

## Just the Docs config - https://pmarsceill.github.io/just-the-docs/docs/configuration/

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Edit with Prose":
    - "//prose.io/#Treefrog/Handbook"
  "View on GitHub":
    - "//github.com/Treefrog/Handbook"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Sort order for navigation links
nav_sort: case_insensitive

## Prose.io config - https://github.com/prose/prose/wiki/Prose-Configuration

prose:
  siteurl: "http://handbook.treefrog.ca"
  media: 'assets/images'
  ignore:
    - .editorconfig
    - .gitignore
    - CNAME
    - Gemfile
    - _config.yml
    - /_includes
    - /_layouts
