remote_theme: pmarsceill/just-the-docs@v0.2.2
title: Treefrog Handbook
lang: en-CA

exclude: ["Blank.md", "BestPractices", "DroppedChanges", "Goals"]

readme_index:
  remove_originals: true

optional_front_matter:
  remove_originals: true

## Just the Docs config - https://pmarsceill.github.io/just-the-docs/docs/configuration/

# Aux links for the upper right navigation
aux_links:
  "Edit with Prose":
    - "//prose.io/#Treefrog/Handbook"
  "View on GitHub":
    - "//github.com/Treefrog/Handbook"
